name 'motd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures motd'
version '0.1.0'
chef_version '>= 14.0'

supports 'centos', '>= 6.0'
supports 'debian', '>= 8.0'
supports 'ubuntu', '>= 16.04'
supports 'windows'